// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReviews.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieReviews.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220829165426_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieReviews.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                            Name = "Superman and Lois"
                        },
                        new
                        {
                            Id = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                            Name = "Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                            Name = "Avengers: Endgame"
                        });
                });

            modelBuilder.Entity("MovieReviews.Models.Movie", b =>
                {
                    b.OwnsMany("MovieReviews.Models.Review", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Reviewer")
                                .HasColumnType("text");

                            b1.Property<int>("Stars")
                                .HasColumnType("integer");

                            b1.HasKey("MovieId", "Id");

                            b1.ToTable("Review");

                            b1.WithOwner()
                                .HasForeignKey("MovieId");

                            b1.HasData(
                                new
                                {
                                    MovieId = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                                    Id = 1,
                                    Reviewer = "A",
                                    Stars = 4
                                },
                                new
                                {
                                    MovieId = new Guid("72d95bfd-1dac-4bc2-adc1-f28fd43777fd"),
                                    Id = 2,
                                    Reviewer = "B",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 3,
                                    Reviewer = "A",
                                    Stars = 4
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 4,
                                    Reviewer = "D",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 5,
                                    Reviewer = "E",
                                    Stars = 3
                                },
                                new
                                {
                                    MovieId = new Guid("c32cc263-a7af-4fbd-99a0-aceb57c91f6b"),
                                    Id = 6,
                                    Reviewer = "F",
                                    Stars = 5
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 7,
                                    Reviewer = "A",
                                    Stars = 2
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 8,
                                    Reviewer = "B",
                                    Stars = 1
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 9,
                                    Reviewer = "G",
                                    Stars = 3
                                },
                                new
                                {
                                    MovieId = new Guid("7b6bf2e3-5d91-4e75-b62f-7357079acc51"),
                                    Id = 10,
                                    Reviewer = "H",
                                    Stars = 4
                                });
                        });

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
